server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?userUnicode=true&characterEncoding=utf-8&userSSL=false
    username: root
    password: 123456

eureka:
  client:
    #表示是否将自己注册进Eureka Server默认为true
    register-with-eureka: true
    #表示是否从Eureka Server抓取已有的注册信息 默认为true 单节点无所谓 集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka/ #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示IP地址
    #Eureka Client向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka Server 在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 60
mybatis:
  mapperLocations: classpath:mapper/*.xml #mapper.xml包路径
  type-aliases-package: com.zcc.springcloud.entities #实体类包路径
