server:
  port: 80

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?userUnicode=true&characterEncoding=utf-8&userSSL=false
    username: root
    password: 123456
mybatis:
  mapperLocations: classpath:mapper/*.xml #mapper.xml包路径
  type-aliases-package: com.zcc.springcloud.entities #实体类包路径
url:
  payment:
    create: http://localhost:8001/api/payment/test/create