package com.zcc.utils.idCardUtil;

/**
 * @author zcc
 * @version 1.0
 * @date 2021/12/15 11:24
 */
public enum Area2 {

    GUANGXIZHUANGZUZIZHIQUNANNINGSHICHENGBEIQU(450104, "广西壮族自治区南宁市城北区"), GUANGXIZHUANGZUZIZHIQUNANNINGSHIJIANGNANQU(450105, "广西壮族自治区南宁市江南区"),

    GUANGXIZHUANGZUZIZHIQUNANNINGSHIYONGXINQU(450106, "广西壮族自治区南宁市永新区"), GUANGXIZHUANGZUZIZHIQUNANNINGSHISHIJIAOQU(450111, "广西壮族自治区南宁市市郊区"),

    GUANGXIZHUANGZUZIZHIQUNANNINGSHIYONGNINGXIAN(450121, "广西壮族自治区南宁市邕宁县"), GUANGXIZHUANGZUZIZHIQUNANNINGSHIWUMINGXIAN(450122, "广西壮族自治区南宁市武鸣县"),

    GUANGXIZHUANGZUZIZHIQULIUZHOUSHI(450200, "广西壮族自治区柳州市"), GUANGXIZHUANGZUZIZHIQULIUZHOUSHISHIXIAQU(450201, "广西壮族自治区柳州市市辖区"),

    GUANGXIZHUANGZUZIZHIQULIUZHOUSHICHENGZHONGQU(450202, "广西壮族自治区柳州市城中区"), GUANGXIZHUANGZUZIZHIQULIUZHOUSHIYUFENGQU(450203, "广西壮族自治区柳州市鱼峰区"),

    GUANGXIZHUANGZUZIZHIQULIUZHOUSHILIUNANQU(450204, "广西壮族自治区柳州市柳南区"), GUANGXIZHUANGZUZIZHIQULIUZHOUSHILIUBEIQU(450205, "广西壮族自治区柳州市柳北区"),

    GUANGXIZHUANGZUZIZHIQULIUZHOUSHISHIJIAOQU(450211, "广西壮族自治区柳州市市郊区"), GUANGXIZHUANGZUZIZHIQULIUZHOUSHILIUJIANGXIAN(450221, "广西壮族自治区柳州市柳江县"),

    GUANGXIZHUANGZUZIZHIQULIUZHOUSHILIUCHENGXIAN(450222, "广西壮族自治区柳州市柳城县"), GUANGXIZHUANGZUZIZHIQUGUILINSHI(450300, "广西壮族自治区桂林市"),

    GUANGXIZHUANGZUZIZHIQUGUILINSHISHIXIAQU(450301, "广西壮族自治区桂林市市辖区"), GUANGXIZHUANGZUZIZHIQUGUILINSHIXIUFENGQU(450302, "广西壮族自治区桂林市秀峰区"),

    GUANGXIZHUANGZUZIZHIQUGUILINSHIDIECAIQU(450303, "广西壮族自治区桂林市叠彩区"), GUANGXIZHUANGZUZIZHIQUGUILINSHIXIANGSHANQU(450304, "广西壮族自治区桂林市象山区"),

    GUANGXIZHUANGZUZIZHIQUGUILINSHIQIXINGQU(450305, "广西壮族自治区桂林市七星区"), GUANGXIZHUANGZUZIZHIQUGUILINSHIYANSHANQU(450311, "广西壮族自治区桂林市雁山区"),

    GUANGXIZHUANGZUZIZHIQUGUILINSHIYANGSHUOXIAN(450321, "广西壮族自治区桂林市阳朔县"), GUANGXIZHUANGZUZIZHIQUGUILINSHILINGUIXIAN(450322, "广西壮族自治区桂林市临桂县"),

    GUANGXIZHUANGZUZIZHIQUGUILINSHILINGCHUANXIAN(450323, "广西壮族自治区桂林市灵川县"), GUANGXIZHUANGZUZIZHIQUGUILINSHIQUANZHOUXIAN(450324, "广西壮族自治区桂林市全州县"),

    GUANGXIZHUANGZUZIZHIQUGUILINSHIXINGANXIAN(450325, "广西壮族自治区桂林市兴安县"), GUANGXIZHUANGZUZIZHIQUGUILINSHIYONGFUXIAN(450326, "广西壮族自治区桂林市永福县"),

    GUANGXIZHUANGZUZIZHIQUGUILINSHIGUANYANGXIAN(450327, "广西壮族自治区桂林市灌阳县"), GUANGXIZHUANGZUZIZHIQUGUILINSHILONGSHENGGEZUZIZHIXIAN(450328, "广西壮族自治区桂林市龙胜各族自治县"),

    GUANGXIZHUANGZUZIZHIQUGUILINSHIZIYUANXIAN(450329, "广西壮族自治区桂林市资源县"), GUANGXIZHUANGZUZIZHIQUGUILINSHIPINGLEXIAN(450330, "广西壮族自治区桂林市平乐县"),

    GUANGXIZHUANGZUZIZHIQUGUILINSHILIPUXIAN(450331, "广西壮族自治区桂林市荔浦县"), GUANGXIZHUANGZUZIZHIQUGUILINSHIGONGCHENGYAOZUZIZHIXIAN(450332, "广西壮族自治区桂林市恭城瑶族自治县"),

    GUANGXIZHUANGZUZIZHIQUWUZHOUSHI(450400, "广西壮族自治区梧州市"), GUANGXIZHUANGZUZIZHIQUWUZHOUSHISHIXIAQU(450401, "广西壮族自治区梧州市市辖区"),

    GUANGXIZHUANGZUZIZHIQUWUZHOUSHIWANXIUQU(450403, "广西壮族自治区梧州市万秀区"), GUANGXIZHUANGZUZIZHIQUWUZHOUSHIDIESHANQU(450404, "广西壮族自治区梧州市蝶山区"),

    GUANGXIZHUANGZUZIZHIQUWUZHOUSHISHIJIAOQU(450411, "广西壮族自治区梧州市市郊区"), GUANGXIZHUANGZUZIZHIQUWUZHOUSHICANGWUXIAN(450421, "广西壮族自治区梧州市苍梧县"),

    GUANGXIZHUANGZUZIZHIQUWUZHOUSHITENGXIAN(450422, "广西壮族自治区梧州市藤县"), GUANGXIZHUANGZUZIZHIQUWUZHOUSHIMENGSHANXIAN(450423, "广西壮族自治区梧州市蒙山县"),

    GUANGXIZHUANGZUZIZHIQUWUZHOUSHICENXISHI(450481, "广西壮族自治区梧州市岑溪市"), GUANGXIZHUANGZUZIZHIQUBEIHAISHI(450500, "广西壮族自治区北海市"),

    GUANGXIZHUANGZUZIZHIQUBEIHAISHISHIXIAQU(450501, "广西壮族自治区北海市市辖区"), GUANGXIZHUANGZUZIZHIQUBEIHAISHIHAICHENGQU(450502, "广西壮族自治区北海市海城区"),

    GUANGXIZHUANGZUZIZHIQUBEIHAISHIYINHAIQU(450503, "广西壮族自治区北海市银海区"), GUANGXIZHUANGZUZIZHIQUBEIHAISHITIESHANGANGQU(450512, "广西壮族自治区北海市铁山港区"),

    GUANGXIZHUANGZUZIZHIQUBEIHAISHIHEPUXIAN(450521, "广西壮族自治区北海市合浦县"), GUANGXIZHUANGZUZIZHIQUFANGCHENGGANGSHI(450600, "广西壮族自治区防城港市"),

    GUANGXIZHUANGZUZIZHIQUFANGCHENGGANGSHISHIXIAQU(450601, "广西壮族自治区防城港市市辖区"), GUANGXIZHUANGZUZIZHIQUFANGCHENGGANGSHIGANGKOUQU(450602, "广西壮族自治区防城港市港口区"),

    GUANGXIZHUANGZUZIZHIQUFANGCHENGGANGSHIFANGCHENGQU(450603, "广西壮族自治区防城港市防城区"), GUANGXIZHUANGZUZIZHIQUFANGCHENGGANGSHISHANGSIXIAN(450621, "广西壮族自治区防城港市上思县"),

    GUANGXIZHUANGZUZIZHIQUFANGCHENGGANGSHIDONGXINGSHI(450681, "广西壮族自治区防城港市东兴市"), GUANGXIZHUANGZUZIZHIQUQINZHOUSHI(450700, "广西壮族自治区钦州市"),

    GUANGXIZHUANGZUZIZHIQUQINZHOUSHISHIXIAQU(450701, "广西壮族自治区钦州市市辖区"), GUANGXIZHUANGZUZIZHIQUQINZHOUSHIQINNANQU(450702, "广西壮族自治区钦州市钦南区"),

    GUANGXIZHUANGZUZIZHIQUQINZHOUSHIQINBEIQU(450703, "广西壮族自治区钦州市钦北区"), GUANGXIZHUANGZUZIZHIQUQINZHOUSHILINGSHANXIAN(450721, "广西壮族自治区钦州市灵山县"),

    GUANGXIZHUANGZUZIZHIQUQINZHOUSHIPUBEIXIAN(450722, "广西壮族自治区钦州市浦北县"), GUANGXIZHUANGZUZIZHIQUGUIGANGSHI(450800, "广西壮族自治区贵港市"),

    GUANGXIZHUANGZUZIZHIQUGUIGANGSHISHIXIAQU(450801, "广西壮族自治区贵港市市辖区"), GUANGXIZHUANGZUZIZHIQUGUIGANGSHIGANGBEIQU(450802, "广西壮族自治区贵港市港北区"),

    GUANGXIZHUANGZUZIZHIQUGUIGANGSHIGANGNANQU(450803, "广西壮族自治区贵港市港南区"), GUANGXIZHUANGZUZIZHIQUGUIGANGSHIPINGNANXIAN(450821, "广西壮族自治区贵港市平南县"),

    GUANGXIZHUANGZUZIZHIQUGUIGANGSHIGUIPINGSHI(450881, "广西壮族自治区贵港市桂平市"), GUANGXIZHUANGZUZIZHIQUYULINSHI(450900, "广西壮族自治区玉林市"),

    GUANGXIZHUANGZUZIZHIQUYULINSHISHIXIAQU(450901, "广西壮族自治区玉林市市辖区"), GUANGXIZHUANGZUZIZHIQUYULINSHIYUZHOUQU(450902, "广西壮族自治区玉林市玉州区"),

    GUANGXIZHUANGZUZIZHIQUYULINSHIRONGXIAN(450921, "广西壮族自治区玉林市容县"), GUANGXIZHUANGZUZIZHIQUYULINSHILUCHUANXIAN(450922, "广西壮族自治区玉林市陆川县"),

    GUANGXIZHUANGZUZIZHIQUYULINSHIBOBAIXIAN(450923, "广西壮族自治区玉林市博白县"), GUANGXIZHUANGZUZIZHIQUYULINSHIXINGYEXIAN(450924, "广西壮族自治区玉林市兴业县"),

    GUANGXIZHUANGZUZIZHIQUYULINSHIBEILIUSHI(450981, "广西壮族自治区玉林市北流市"), GUANGXIZHUANGZUZIZHIQUNANNINGDIQU(452100, "广西壮族自治区南宁地区"),

    GUANGXIZHUANGZUZIZHIQUNANNINGDIQUPINGXIANGSHI(452101, "广西壮族自治区南宁地区凭祥市"), GUANGXIZHUANGZUZIZHIQUNANNINGDIQUHENGXIAN(452122, "广西壮族自治区南宁地区横县"),

    GUANGXIZHUANGZUZIZHIQUNANNINGDIQUBINYANGXIAN(452123, "广西壮族自治区南宁地区宾阳县"), GUANGXIZHUANGZUZIZHIQUNANNINGDIQUSHANGLINXIAN(452124, "广西壮族自治区南宁地区上林县"),

    GUANGXIZHUANGZUZIZHIQUNANNINGDIQULONGANXIAN(452126, "广西壮族自治区南宁地区隆安县"), GUANGXIZHUANGZUZIZHIQUNANNINGDIQUMASHANXIAN(452127, "广西壮族自治区南宁地区马山县"),

    GUANGXIZHUANGZUZIZHIQUNANNINGDIQUFUSUIXIAN(452128, "广西壮族自治区南宁地区扶绥县"), GUANGXIZHUANGZUZIZHIQUNANNINGDIQUCHONGZUOXIAN(452129, "广西壮族自治区南宁地区崇左县"),

    GUANGXIZHUANGZUZIZHIQUNANNINGDIQUDAXINXIAN(452130, "广西壮族自治区南宁地区大新县"), GUANGXIZHUANGZUZIZHIQUNANNINGDIQUTIANDENGXIAN(452131, "广西壮族自治区南宁地区天等县"),

    GUANGXIZHUANGZUZIZHIQUNANNINGDIQUNINGMINGXIAN(452132, "广西壮族自治区南宁地区宁明县"), GUANGXIZHUANGZUZIZHIQUNANNINGDIQULONGZHOUXIAN(452133, "广西壮族自治区南宁地区龙州县"),

    GUANGXIZHUANGZUZIZHIQULIUZHOUDIQU(452200, "广西壮族自治区柳州地区"), GUANGXIZHUANGZUZIZHIQULIUZHOUDIQUHESHANSHI(452201, "广西壮族自治区柳州地区合山市"),

    GUANGXIZHUANGZUZIZHIQULIUZHOUDIQULUZHAIXIAN(452223, "广西壮族自治区柳州地区鹿寨县"), GUANGXIZHUANGZUZIZHIQULIUZHOUDIQUXIANGZHOUXIAN(452224, "广西壮族自治区柳州地区象州县"),

    GUANGXIZHUANGZUZIZHIQULIUZHOUDIQUWUXUANXIAN(452225, "广西壮族自治区柳州地区武宣县"), GUANGXIZHUANGZUZIZHIQULIUZHOUDIQULAIBINXIAN(452226, "广西壮族自治区柳州地区来宾县"),

    GUANGXIZHUANGZUZIZHIQULIUZHOUDIQURONGANXIAN(452227, "广西壮族自治区柳州地区融安县"), GUANGXIZHUANGZUZIZHIQULIUZHOUDIQUSANJIANGDONGZUZIZHIXIAN(452228, "广西壮族自治区柳州地区三江侗族自治县"),

    GUANGXIZHUANGZUZIZHIQULIUZHOUDIQURONGSHUIMIAOZUZIZHIXIAN(452229, "广西壮族自治区柳州地区融水苗族自治县"), GUANGXIZHUANGZUZIZHIQULIUZHOUDIQUJINXIUYAOZUZIZHIXIAN(452230, "广西壮族自治区柳州地区金秀瑶族自治县"),

    GUANGXIZHUANGZUZIZHIQULIUZHOUDIQUXINCHENGXIAN(452231, "广西壮族自治区柳州地区忻城县"), GUANGXIZHUANGZUZIZHIQUHEZHOUDIQU(452400, "广西壮族自治区贺州地区"),

    GUANGXIZHUANGZUZIZHIQUHEZHOUDIQUHEZHOUSHI(452402, "广西壮族自治区贺州地区贺州市"), GUANGXIZHUANGZUZIZHIQUHEZHOUDIQUZHAOPINGXIAN(452424, "广西壮族自治区贺州地区昭平县"),

    GUANGXIZHUANGZUZIZHIQUHEZHOUDIQUZHONGSHANXIAN(452427, "广西壮族自治区贺州地区钟山县"), GUANGXIZHUANGZUZIZHIQUHEZHOUDIQUFUCHUANYAOZUZIZHIXIAN(452428, "广西壮族自治区贺州地区富川瑶族自治县"),

    GUANGXIZHUANGZUZIZHIQUBAISEDIQU(452600, "广西壮族自治区百色地区"), GUANGXIZHUANGZUZIZHIQUBAISEDIQUBAISESHI(452601, "广西壮族自治区百色地区百色市"),

    GUANGXIZHUANGZUZIZHIQUBAISEDIQUTIANYANGXIAN(452622, "广西壮族自治区百色地区田阳县"), GUANGXIZHUANGZUZIZHIQUBAISEDIQUTIANDONGXIAN(452623, "广西壮族自治区百色地区田东县"),

    GUANGXIZHUANGZUZIZHIQUBAISEDIQUPINGGUOXIAN(452624, "广西壮族自治区百色地区平果县"), GUANGXIZHUANGZUZIZHIQUBAISEDIQUDEBAOXIAN(452625, "广西壮族自治区百色地区德保县"),

    GUANGXIZHUANGZUZIZHIQUBAISEDIQUJINGXIXIAN(452626, "广西壮族自治区百色地区靖西县"), GUANGXIZHUANGZUZIZHIQUBAISEDIQUNEIPOXIAN(452627, "广西壮族自治区百色地区那坡县"),

    GUANGXIZHUANGZUZIZHIQUBAISEDIQULINGYUNXIAN(452628, "广西壮族自治区百色地区凌云县"), GUANGXIZHUANGZUZIZHIQUBAISEDIQULEYEXIAN(452629, "广西壮族自治区百色地区乐业县"),

    GUANGXIZHUANGZUZIZHIQUBAISEDIQUTIANLINXIAN(452630, "广西壮族自治区百色地区田林县"), GUANGXIZHUANGZUZIZHIQUBAISEDIQULONGLINGEZUZIZHIXIAN(452631, "广西壮族自治区百色地区隆林各族自治县"),

    GUANGXIZHUANGZUZIZHIQUBAISEDIQUXILINXIAN(452632, "广西壮族自治区百色地区西林县"), GUANGXIZHUANGZUZIZHIQUHECHIDIQU(452700, "广西壮族自治区河池地区"),

    GUANGXIZHUANGZUZIZHIQUHECHIDIQUHECHISHI(452701, "广西壮族自治区河池地区河池市"), GUANGXIZHUANGZUZIZHIQUHECHIDIQUYIZHOUSHI(452702, "广西壮族自治区河池地区宜州市"),

    GUANGXIZHUANGZUZIZHIQUHECHIDIQULUOCHENGMULAOZUZIZHIXIAN(452723, "广西壮族自治区河池地区罗城仫佬族自治县"), GUANGXIZHUANGZUZIZHIQUHECHIDIQUHUANJIANGMAONANZUZIZHIXIAN(452724, "广西壮族自治区河池地区环江毛南族自治县"),

    GUANGXIZHUANGZUZIZHIQUHECHIDIQUNANDANXIAN(452725, "广西壮族自治区河池地区南丹县"), GUANGXIZHUANGZUZIZHIQUHECHIDIQUTIANEXIAN(452726, "广西壮族自治区河池地区天峨县"),

    GUANGXIZHUANGZUZIZHIQUHECHIDIQUFENGSHANXIAN(452727, "广西壮族自治区河池地区凤山县"), GUANGXIZHUANGZUZIZHIQUHECHIDIQUDONGLANXIAN(452728, "广西壮族自治区河池地区东兰县"),

    GUANGXIZHUANGZUZIZHIQUHECHIDIQUBAMAYAOZUZIZHIXIAN(452729, "广西壮族自治区河池地区巴马瑶族自治县"), GUANGXIZHUANGZUZIZHIQUHECHIDIQUDOUANYAOZUZIZHIXIAN(452730, "广西壮族自治区河池地区都安瑶族自治县"),

    GUANGXIZHUANGZUZIZHIQUHECHIDIQUDAHUAYAOZUZIZHIXIAN(452731, "广西壮族自治区河池地区大化瑶族自治县"), HAINANSHENG(460000, "海南省"),

    HAINANSHENGSANYASHITONGSHENSHI(460001, "海南省三亚市通什市"), HAINANSHENGSANYASHIQIONGHAISHI(460002, "海南省三亚市琼海市"),

    HAINANSHENGSANYASHIDANZHOUSHI(460003, "海南省三亚市儋州市"), HAINANSHENGSANYASHIQIONGSHANSHI(460004, "海南省三亚市琼山市"),

    HAINANSHENGSANYASHIWENCHANGSHI(460005, "海南省三亚市文昌市"), HAINANSHENGSANYASHIWANNINGSHI(460006, "海南省三亚市万宁市"),

    HAINANSHENGSANYASHIDONGFANGSHI(460007, "海南省三亚市东方市"), HAINANSHENGSANYASHIDINGANXIAN(460025, "海南省三亚市定安县"),

    HAINANSHENGSANYASHITUNCHANGXIAN(460026, "海南省三亚市屯昌县"), HAINANSHENGSANYASHICHENGMAIXIAN(460027, "海南省三亚市澄迈县"),

    HAINANSHENGSANYASHILINGAOXIAN(460028, "海南省三亚市临高县"), HAINANSHENGSANYASHIBAISHALIZUZIZHIXIAN(460030, "海南省三亚市白沙黎族自治县"),

    HAINANSHENGSANYASHICHANGJIANGLIZUZIZHIXIAN(460031, "海南省三亚市昌江黎族自治县"), HAINANSHENGSANYASHILEDONGLIZUZIZHIXIAN(460033, "海南省三亚市乐东黎族自治县"),

    HAINANSHENGSANYASHILINGSHUILIZUZIZHIXIAN(460034, "海南省三亚市陵水黎族自治县"), HAINANSHENGSANYASHIBAOTINGLIZUMIAOZUZIZHIXIAN(460035, "海南省三亚市保亭黎族苗族自治县"),

    HAINANSHENGSANYASHIQIONGZHONGLIZUMIAOZUZIZHIXIAN(460036, "海南省三亚市琼中黎族苗族自治县"), HAINANSHENGXISHAQUNDAO(460037, "海南省西沙群岛"),

    HAINANSHENGNANSHAQUNDAO(460038, "海南省南沙群岛"), HAINANSHENGZHONGSHAQUNDAODEDAOJIAOJIQIHAIYU(460039, "海南省中沙群岛的岛礁及其海域"),

    HAINANSHENGHAIKOUSHI(460100, "海南省海口市"), HAINANSHENGHAIKOUSHISHIXIAQU(460101, "海南省海口市市辖区"),

    HAINANSHENGHAIKOUSHIZHENDONGQU(460102, "海南省海口市振东区"), HAINANSHENGHAIKOUSHIXINHUAQU(460103, "海南省海口市新华区"),

    HAINANSHENGHAIKOUSHIXIUYINGQU(460104, "海南省海口市秀英区"), HAINANSHENGSANYASHI(460200, "海南省三亚市"),

    HAINANSHENGSANYASHISHIXIAQU(460201, "海南省三亚市市辖区"), ZHONGQINGSHI(500000, "重庆市"),

    ZHONGQINGSHISHIXIAQU(500100, "重庆市市辖区"), ZHONGQINGSHIWANZHOUQU(500101, "重庆市万州区"),

    ZHONGQINGSHIFULINGQU(500102, "重庆市涪陵区"), ZHONGQINGSHIYUZHONGQU(500103, "重庆市渝中区"),

    ZHONGQINGSHIDADUKOUQU(500104, "重庆市大渡口区"), ZHONGQINGSHIJIANGBEIQU(500105, "重庆市江北区"),

    ZHONGQINGSHISHAPINGBAQU(500106, "重庆市沙坪坝区"), ZHONGQINGSHIJIULONGPOQU(500107, "重庆市九龙坡区"),

    ZHONGQINGSHINANANQU(500108, "重庆市南岸区"), ZHONGQINGSHIBEIBEIQU(500109, "重庆市北碚区"),

    ZHONGQINGSHIWANSHENGQU(500110, "重庆市万盛区"), ZHONGQINGSHISHUANGQIAOQU(500111, "重庆市双桥区"),

    ZHONGQINGSHIYUBEIQU(500112, "重庆市渝北区"), ZHONGQINGSHIBANANQU(500113, "重庆市巴南区"),

    ZHONGQINGSHIXIAN(500200, "重庆市县"), ZHONGQINGSHIZHANGSHOUXIAN(500221, "重庆市长寿县"),

    ZHONGQINGSHIQIJIANGXIAN(500222, "重庆市綦江县"), ZHONGQINGSHITONGNANXIAN(500223, "重庆市潼南县"),

    ZHONGQINGSHITONGLIANGXIAN(500224, "重庆市铜梁县"), ZHONGQINGSHIDAZUXIAN(500225, "重庆市大足县"),

    ZHONGQINGSHIRONGCHANGXIAN(500226, "重庆市荣昌县"), ZHONGQINGSHIBISHANXIAN(500227, "重庆市璧山县"),

    ZHONGQINGSHILIANGPINGXIAN(500228, "重庆市梁平县"), ZHONGQINGSHICHENGKOUXIAN(500229, "重庆市城口县"),

    ZHONGQINGSHIFENGDOUXIAN(500230, "重庆市丰都县"), ZHONGQINGSHIDIANJIANGXIAN(500231, "重庆市垫江县"),

    ZHONGQINGSHIWULONGXIAN(500232, "重庆市武隆县"), ZHONGQINGSHIZHONGXIAN(500233, "重庆市忠县"),

    ZHONGQINGSHIKAIXIAN(500234, "重庆市开县"), ZHONGQINGSHIYUNYANGXIAN(500235, "重庆市云阳县"),

    ZHONGQINGSHIFENGJIEXIAN(500236, "重庆市奉节县"), ZHONGQINGSHIWUSHANXIAN(500237, "重庆市巫山县"),

    ZHONGQINGSHIWUXIXIAN(500238, "重庆市巫溪县"), ZHONGQINGSHIQIANJIANGTUJIAZUMIAOZUZIZHIXIAN(500239, "重庆市黔江土家族苗族自治县"),

    ZHONGQINGSHISHIZHUTUJIAZUZIZHIXIAN(500240, "重庆市石柱土家族自治县"), ZHONGQINGSHIXIUSHANTUJIAZUMIAOZUZIZHIXIAN(500241, "重庆市秀山土家族苗族自治县"),

    ZHONGQINGSHIYOUYANGTUJIAZUMIAOZUZIZHIXIAN(500242, "重庆市酉阳土家族苗族自治县"), ZHONGQINGSHIPENGSHUIMIAOZUTUJIAZUZIZHIXIAN(500243, "重庆市彭水苗族土家族自治县"),

//        ZHONGQINGSHI(500300,"重庆市"),

    ZHONGQINGSHIJIANGJINSHI(500381, "重庆市江津市"), ZHONGQINGSHIHECHUANSHI(500382, "重庆市合川市"),

    ZHONGQINGSHIYONGCHUANSHI(500383, "重庆市永川市"), ZHONGQINGSHINANCHUANSHI(500384, "重庆市南川市"),

    SICHUANSHENG(510000, "四川省"), SICHUANSHENGCHENGDOUSHI(510100, "四川省成都市"),

    SICHUANSHENGCHENGDOUSHISHIXIAQU(510101, "四川省成都市市辖区"), SICHUANSHENGCHENGDOUSHIJINJIANGQU(510104, "四川省成都市锦江区"),

    SICHUANSHENGCHENGDOUSHIQINGYANGQU(510105, "四川省成都市青羊区"), SICHUANSHENGCHENGDOUSHIJINNIUQU(510106, "四川省成都市金牛区"),

    SICHUANSHENGCHENGDOUSHIWUHOUQU(510107, "四川省成都市武侯区"), SICHUANSHENGCHENGDOUSHICHENGHUAQU(510108, "四川省成都市成华区"),

    SICHUANSHENGCHENGDOUSHILONGQUANYIQU(510112, "四川省成都市龙泉驿区"), SICHUANSHENGCHENGDOUSHIQINGBAIJIANGQU(510113, "四川省成都市青白江区"),

    SICHUANSHENGCHENGDOUSHIJINTANGXIAN(510121, "四川省成都市金堂县"), SICHUANSHENGCHENGDOUSHISHUANGLIUXIAN(510122, "四川省成都市双流县"),

    SICHUANSHENGCHENGDOUSHIWENJIANGXIAN(510123, "四川省成都市温江县"), SICHUANSHENGCHENGDOUSHIPIXIAN(510124, "四川省成都市郫县"),

    SICHUANSHENGCHENGDOUSHIXINDOUXIAN(510125, "四川省成都市新都县"), SICHUANSHENGCHENGDOUSHIDAYIXIAN(510129, "四川省成都市大邑县"),

    SICHUANSHENGCHENGDOUSHIPUJIANGXIAN(510131, "四川省成都市蒲江县"), SICHUANSHENGCHENGDOUSHIXINJINXIAN(510132, "四川省成都市新津县"),

    SICHUANSHENGCHENGDOUSHIDOUJIANGYANSHI(510181, "四川省成都市都江堰市"), SICHUANSHENGCHENGDOUSHIPENGZHOUSHI(510182, "四川省成都市彭州市"),

    SICHUANSHENGCHENGDOUSHIQIONGLAISHI(510183, "四川省成都市邛崃市"), SICHUANSHENGCHENGDOUSHICHONGZHOUSHI(510184, "四川省成都市崇州市"),

    SICHUANSHENGZIGONGSHI(510300, "四川省自贡市"), SICHUANSHENGZIGONGSHISHIXIAQU(510301, "四川省自贡市市辖区"),

    SICHUANSHENGZIGONGSHIZILIUJINGQU(510302, "四川省自贡市自流井区"), SICHUANSHENGZIGONGSHIGONGJINGQU(510303, "四川省自贡市贡井区"),

    SICHUANSHENGZIGONGSHIDAANQU(510304, "四川省自贡市大安区"), SICHUANSHENGZIGONGSHIYANTANQU(510311, "四川省自贡市沿滩区"),

    SICHUANSHENGZIGONGSHIRONGXIAN(510321, "四川省自贡市荣县"), SICHUANSHENGZIGONGSHIFUSHUNXIAN(510322, "四川省自贡市富顺县"),

    SICHUANSHENGPANZHIHUASHI(510400, "四川省攀枝花市"), SICHUANSHENGPANZHIHUASHISHIXIAQU(510401, "四川省攀枝花市市辖区"),

    SICHUANSHENGPANZHIHUASHIDONGQU(510402, "四川省攀枝花市东区"), SICHUANSHENGPANZHIHUASHIXIQU(510403, "四川省攀枝花市西区"),

    SICHUANSHENGPANZHIHUASHIRENHEQU(510411, "四川省攀枝花市仁和区"), SICHUANSHENGPANZHIHUASHIMIYIXIAN(510421, "四川省攀枝花市米易县"),

    SICHUANSHENGPANZHIHUASHIYANBIANXIAN(510422, "四川省攀枝花市盐边县"), SICHUANSHENGLUZHOUSHI(510500, "四川省泸州市"),

    SICHUANSHENGLUZHOUSHISHIXIAQU(510501, "四川省泸州市市辖区"), SICHUANSHENGLUZHOUSHIJIANGYANGQU(510502, "四川省泸州市江阳区"),

    SICHUANSHENGLUZHOUSHINAXIQU(510503, "四川省泸州市纳溪区"), SICHUANSHENGLUZHOUSHILONGMATANQU(510504, "四川省泸州市龙马潭区"),

    SICHUANSHENGLUZHOUSHILUXIAN(510521, "四川省泸州市泸县"), SICHUANSHENGLUZHOUSHIHEJIANGXIAN(510522, "四川省泸州市合江县"),

    SICHUANSHENGLUZHOUSHIXUYONGXIAN(510524, "四川省泸州市叙永县"), SICHUANSHENGLUZHOUSHIGULINXIAN(510525, "四川省泸州市古蔺县"),

    SICHUANSHENGDEYANGSHI(510600, "四川省德阳市"), SICHUANSHENGDEYANGSHISHIXIAQU(510601, "四川省德阳市市辖区"),

    SICHUANSHENGDEYANGSHIJINGYANGQU(510603, "四川省德阳市旌阳区"), SICHUANSHENGDEYANGSHIZHONGJIANGXIAN(510623, "四川省德阳市中江县"),

    SICHUANSHENGDEYANGSHILUOJIANGXIAN(510626, "四川省德阳市罗江县"), SICHUANSHENGDEYANGSHIGUANGHANSHI(510681, "四川省德阳市广汉市"),

    SICHUANSHENGDEYANGSHISHENFANGSHI(510682, "四川省德阳市什邡市"), SICHUANSHENGDEYANGSHIMIANZHUSHI(510683, "四川省德阳市绵竹市"),

    SICHUANSHENGMIANYANGSHI(510700, "四川省绵阳市"), SICHUANSHENGMIANYANGSHISHIXIAQU(510701, "四川省绵阳市市辖区"),

    SICHUANSHENGMIANYANGSHIFUCHENGQU(510703, "四川省绵阳市涪城区"), SICHUANSHENGMIANYANGSHIYOUXIANQU(510704, "四川省绵阳市游仙区"),

    SICHUANSHENGMIANYANGSHISANTAIXIAN(510722, "四川省绵阳市三台县"), SICHUANSHENGMIANYANGSHIYANTINGXIAN(510723, "四川省绵阳市盐亭县"),

    SICHUANSHENGMIANYANGSHIANXIAN(510724, "四川省绵阳市安县"), SICHUANSHENGMIANYANGSHIZITONGXIAN(510725, "四川省绵阳市梓潼县"),

    SICHUANSHENGMIANYANGSHIBEICHUANXIAN(510726, "四川省绵阳市北川县"), SICHUANSHENGMIANYANGSHIPINGWUXIAN(510727, "四川省绵阳市平武县"),

    SICHUANSHENGMIANYANGSHIJIANGYOUSHI(510781, "四川省绵阳市江油市"), SICHUANSHENGGUANGYUANSHI(510800, "四川省广元市"),

    SICHUANSHENGGUANGYUANSHISHIXIAQU(510801, "四川省广元市市辖区"), SICHUANSHENGGUANGYUANSHISHIZHONGQU(510802, "四川省广元市市中区"),

    SICHUANSHENGGUANGYUANSHIYUANBAQU(510811, "四川省广元市元坝区"), SICHUANSHENGGUANGYUANSHICHAOTIANQU(510812, "四川省广元市朝天区"),

    SICHUANSHENGGUANGYUANSHIWANGCANGXIAN(510821, "四川省广元市旺苍县"), SICHUANSHENGGUANGYUANSHIQINGCHUANXIAN(510822, "四川省广元市青川县"),

    SICHUANSHENGGUANGYUANSHIJIANGEXIAN(510823, "四川省广元市剑阁县"), SICHUANSHENGGUANGYUANSHICANGXIXIAN(510824, "四川省广元市苍溪县"),

    SICHUANSHENGSUININGSHI(510900, "四川省遂宁市"), SICHUANSHENGSUININGSHISHIXIAQU(510901, "四川省遂宁市市辖区"),

    SICHUANSHENGSUININGSHISHIZHONGQU(510902, "四川省遂宁市市中区"), SICHUANSHENGSUININGSHIPENGXIXIAN(510921, "四川省遂宁市蓬溪县"),

    SICHUANSHENGSUININGSHISHEHONGXIAN(510922, "四川省遂宁市射洪县"), SICHUANSHENGSUININGSHIDAYINGXIAN(510923, "四川省遂宁市大英县"),

    SICHUANSHENGNEIJIANGSHI(511000, "四川省内江市"), SICHUANSHENGNEIJIANGSHISHIXIAQU(511001, "四川省内江市市辖区"),

    SICHUANSHENGNEIJIANGSHISHIZHONGQU(511002, "四川省内江市市中区"), SICHUANSHENGNEIJIANGSHIDONGXINGQU(511011, "四川省内江市东兴区"),

    SICHUANSHENGNEIJIANGSHIWEIYUANXIAN(511024, "四川省内江市威远县"), SICHUANSHENGNEIJIANGSHIZIZHONGXIAN(511025, "四川省内江市资中县"),

    SICHUANSHENGNEIJIANGSHILONGCHANGXIAN(511028, "四川省内江市隆昌县"), SICHUANSHENGLESHANSHI(511100, "四川省乐山市"),

    SICHUANSHENGLESHANSHISHIXIAQU(511101, "四川省乐山市市辖区"), SICHUANSHENGLESHANSHISHIZHONGQU(511102, "四川省乐山市市中区"),

    SICHUANSHENGLESHANSHISHAWANQU(511111, "四川省乐山市沙湾区"), SICHUANSHENGLESHANSHIWUTONGQIAOQU(511112, "四川省乐山市五通桥区"),

    SICHUANSHENGLESHANSHIJINKOUHEQU(511113, "四川省乐山市金口河区"), SICHUANSHENGLESHANSHIJIANWEIXIAN(511123, "四川省乐山市犍为县"),

    SICHUANSHENGLESHANSHIJINGYANXIAN(511124, "四川省乐山市井研县"), SICHUANSHENGLESHANSHIJIAJIANGXIAN(511126, "四川省乐山市夹江县"),

    SICHUANSHENGLESHANSHIMUCHUANXIAN(511129, "四川省乐山市沐川县"), SICHUANSHENGLESHANSHIEBIANYIZUZIZHIXIAN(511132, "四川省乐山市峨边彝族自治县"),

    SICHUANSHENGLESHANSHIMABIANYIZUZIZHIXIAN(511133, "四川省乐山市马边彝族自治县"), SICHUANSHENGLESHANSHIEMEISHANSHI(511181, "四川省乐山市峨眉山市"),

    SICHUANSHENGNANCHONGSHI(511300, "四川省南充市"), SICHUANSHENGNANCHONGSHISHIXIAQU(511301, "四川省南充市市辖区"),

    SICHUANSHENGNANCHONGSHISHUNQINGQU(511302, "四川省南充市顺庆区"), SICHUANSHENGNANCHONGSHIGAOPINGQU(511303, "四川省南充市高坪区"),

    SICHUANSHENGNANCHONGSHIJIALINGQU(511304, "四川省南充市嘉陵区"), SICHUANSHENGNANCHONGSHINANBUXIAN(511321, "四川省南充市南部县"),

    SICHUANSHENGNANCHONGSHIYINGSHANXIAN(511322, "四川省南充市营山县"), SICHUANSHENGNANCHONGSHIPENGANXIAN(511323, "四川省南充市蓬安县"),

    SICHUANSHENGNANCHONGSHIYILONGXIAN(511324, "四川省南充市仪陇县"), SICHUANSHENGNANCHONGSHIXICHONGXIAN(511325, "四川省南充市西充县"),

    SICHUANSHENGNANCHONGSHILANGZHONGSHI(511381, "四川省南充市阆中市"), SICHUANSHENGYIBINSHI(511500, "四川省宜宾市"),

    SICHUANSHENGYIBINSHISHIXIAQU(511501, "四川省宜宾市市辖区"), SICHUANSHENGYIBINSHICUIPINGQU(511502, "四川省宜宾市翠屏区"),

    SICHUANSHENGYIBINSHIYIBINXIAN(511521, "四川省宜宾市宜宾县"), SICHUANSHENGYIBINSHINANXIXIAN(511522, "四川省宜宾市南溪县"),

    SICHUANSHENGYIBINSHIJIANGANXIAN(511523, "四川省宜宾市江安县"), SICHUANSHENGYIBINSHIZHANGNINGXIAN(511524, "四川省宜宾市长宁县"),

    SICHUANSHENGYIBINSHIGAOXIAN(511525, "四川省宜宾市高县"), SICHUANSHENGYIBINSHIGONGXIAN(511526, "四川省宜宾市珙县"),

    SICHUANSHENGYIBINSHIYUNLIANXIAN(511527, "四川省宜宾市筠连县"), SICHUANSHENGYIBINSHIXINGWENXIAN(511528, "四川省宜宾市兴文县"),

    SICHUANSHENGYIBINSHIPINGSHANXIAN(511529, "四川省宜宾市屏山县"), SICHUANSHENGGUANGANSHI(511600, "四川省广安市"),

    SICHUANSHENGGUANGANSHISHIXIAQU(511601, "四川省广安市市辖区"), SICHUANSHENGGUANGANSHIGUANGANQU(511602, "四川省广安市广安区"),

    SICHUANSHENGGUANGANSHIYUECHIXIAN(511621, "四川省广安市岳池县"), SICHUANSHENGGUANGANSHIWUSHENGXIAN(511622, "四川省广安市武胜县"),

    SICHUANSHENGGUANGANSHILINSHUIXIAN(511623, "四川省广安市邻水县"), SICHUANSHENGGUANGANSHIHUAYINGSHI(511681, "四川省广安市华蓥市"),

    SICHUANSHENGDACHUANDIQU(513000, "四川省达川地区"), SICHUANSHENGDACHUANDIQUDACHUANSHI(513001, "四川省达川地区达川市"),

    SICHUANSHENGDACHUANDIQUWANYUANSHI(513002, "四川省达川地区万源市"), SICHUANSHENGDACHUANDIQUDAXIAN(513021, "四川省达川地区达县"),

    SICHUANSHENGDACHUANDIQUXUANHANXIAN(513022, "四川省达川地区宣汉县"), SICHUANSHENGDACHUANDIQUKAIJIANGXIAN(513023, "四川省达川地区开江县"),

    SICHUANSHENGDACHUANDIQUDAZHUXIAN(513029, "四川省达川地区大竹县"), SICHUANSHENGDACHUANDIQUQUXIAN(513030, "四川省达川地区渠县"),

    SICHUANSHENGYAANDIQU(513100, "四川省雅安地区"), SICHUANSHENGYAANDIQUYAANSHI(513101, "四川省雅安地区雅安市"),

    SICHUANSHENGYAANDIQUMINGSHANXIAN(513122, "四川省雅安地区名山县"), SICHUANSHENGYAANDIQUYINGJINGXIAN(513123, "四川省雅安地区荥经县"),

    SICHUANSHENGYAANDIQUHANYUANXIAN(513124, "四川省雅安地区汉源县"), SICHUANSHENGYAANDIQUSHIMIANXIAN(513125, "四川省雅安地区石棉县"),

    SICHUANSHENGYAANDIQUTIANQUANXIAN(513126, "四川省雅安地区天全县"), SICHUANSHENGYAANDIQULUSHANXIAN(513127, "四川省雅安地区芦山县"),

    SICHUANSHENGYAANDIQUBAOXINGXIAN(513128, "四川省雅安地区宝兴县"), SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOU(513200, "四川省阿坝藏族羌族自治州"),

    SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOUWENCHUANXIAN(513221, "四川省阿坝藏族羌族自治州汶川县"), SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOULIXIAN(513222, "四川省阿坝藏族羌族自治州理县"),

    SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOUMAOXIAN(513223, "四川省阿坝藏族羌族自治州茂县"), SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOUSONGPANXIAN(513224, "四川省阿坝藏族羌族自治州松潘县"),

    SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOUJIUZHAIGOUXIAN(513225, "四川省阿坝藏族羌族自治州九寨沟县"), SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOUJINCHUANXIAN(513226, "四川省阿坝藏族羌族自治州金川县"),

    SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOUXIAOJINXIAN(513227, "四川省阿坝藏族羌族自治州小金县"), SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOUHEISHUIXIAN(513228, "四川省阿坝藏族羌族自治州黑水县"),

    SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOUMAERKANGXIAN(513229, "四川省阿坝藏族羌族自治州马尔康县"), SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOURANGTANGXIAN(513230, "四川省阿坝藏族羌族自治州壤塘县"),

    SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOUABAXIAN(513231, "四川省阿坝藏族羌族自治州阿坝县"), SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOURUOERGAIXIAN(513232, "四川省阿坝藏族羌族自治州若尔盖县"),

    SICHUANSHENGABAZANGZUQIANGZUZIZHIZHOUHONGYUANXIAN(513233, "四川省阿坝藏族羌族自治州红原县"), SICHUANSHENGGANZIZANGZUZIZHIZHOU(513300, "四川省甘孜藏族自治州"),

    SICHUANSHENGGANZIZANGZUZIZHIZHOUKANGDINGXIAN(513321, "四川省甘孜藏族自治州康定县"), SICHUANSHENGGANZIZANGZUZIZHIZHOULUDINGXIAN(513322, "四川省甘孜藏族自治州泸定县"),

    SICHUANSHENGGANZIZANGZUZIZHIZHOUDANBAXIAN(513323, "四川省甘孜藏族自治州丹巴县"), SICHUANSHENGGANZIZANGZUZIZHIZHOUJIULONGXIAN(513324, "四川省甘孜藏族自治州九龙县"),

    SICHUANSHENGGANZIZANGZUZIZHIZHOUYAJIANGXIAN(513325, "四川省甘孜藏族自治州雅江县"), SICHUANSHENGGANZIZANGZUZIZHIZHOUDAOFUXIAN(513326, "四川省甘孜藏族自治州道孚县"),

    SICHUANSHENGGANZIZANGZUZIZHIZHOULUHUOXIAN(513327, "四川省甘孜藏族自治州炉霍县"), SICHUANSHENGGANZIZANGZUZIZHIZHOUGANZIXIAN(513328, "四川省甘孜藏族自治州甘孜县"),

    SICHUANSHENGGANZIZANGZUZIZHIZHOUXINLONGXIAN(513329, "四川省甘孜藏族自治州新龙县"), SICHUANSHENGGANZIZANGZUZIZHIZHOUDEGEXIAN(513330, "四川省甘孜藏族自治州德格县"),

    SICHUANSHENGGANZIZANGZUZIZHIZHOUBAIYUXIAN(513331, "四川省甘孜藏族自治州白玉县"), SICHUANSHENGGANZIZANGZUZIZHIZHOUSHIQUXIAN(513332, "四川省甘孜藏族自治州石渠县"),

    SICHUANSHENGGANZIZANGZUZIZHIZHOUSEDAXIAN(513333, "四川省甘孜藏族自治州色达县"), SICHUANSHENGGANZIZANGZUZIZHIZHOULITANGXIAN(513334, "四川省甘孜藏族自治州理塘县"),

    SICHUANSHENGGANZIZANGZUZIZHIZHOUBATANGXIAN(513335, "四川省甘孜藏族自治州巴塘县"), SICHUANSHENGGANZIZANGZUZIZHIZHOUXIANGCHENGXIAN(513336, "四川省甘孜藏族自治州乡城县"),

    SICHUANSHENGGANZIZANGZUZIZHIZHOUDAOCHENGXIAN(513337, "四川省甘孜藏族自治州稻城县"), SICHUANSHENGGANZIZANGZUZIZHIZHOUDERONGXIAN(513338, "四川省甘孜藏族自治州得荣县"),

    SICHUANSHENGLIANGSHANYIZUZIZHIZHOU(513400, "四川省凉山彝族自治州"), SICHUANSHENGLIANGSHANYIZUZIZHIZHOUXICHANGSHI(513401, "四川省凉山彝族自治州西昌市"),

    SICHUANSHENGLIANGSHANYIZUZIZHIZHOUMULIZANGZUZIZHIXIAN(513422, "四川省凉山彝族自治州木里藏族自治县"), SICHUANSHENGLIANGSHANYIZUZIZHIZHOUYANYUANXIAN(513423, "四川省凉山彝族自治州盐源县"),

    SICHUANSHENGLIANGSHANYIZUZIZHIZHOUDECHANGXIAN(513424, "四川省凉山彝族自治州德昌县"), SICHUANSHENGLIANGSHANYIZUZIZHIZHOUHUILIXIAN(513425, "四川省凉山彝族自治州会理县"),

    SICHUANSHENGLIANGSHANYIZUZIZHIZHOUHUIDONGXIAN(513426, "四川省凉山彝族自治州会东县"), SICHUANSHENGLIANGSHANYIZUZIZHIZHOUNINGNANXIAN(513427, "四川省凉山彝族自治州宁南县"),

    SICHUANSHENGLIANGSHANYIZUZIZHIZHOUPUGEXIAN(513428, "四川省凉山彝族自治州普格县"), SICHUANSHENGLIANGSHANYIZUZIZHIZHOUBUTUOXIAN(513429, "四川省凉山彝族自治州布拖县"),

    SICHUANSHENGLIANGSHANYIZUZIZHIZHOUJINYANGXIAN(513430, "四川省凉山彝族自治州金阳县"), SICHUANSHENGLIANGSHANYIZUZIZHIZHOUZHAOJUEXIAN(513431, "四川省凉山彝族自治州昭觉县"),

    SICHUANSHENGLIANGSHANYIZUZIZHIZHOUXIDEXIAN(513432, "四川省凉山彝族自治州喜德县"), SICHUANSHENGLIANGSHANYIZUZIZHIZHOUMIANNINGXIAN(513433, "四川省凉山彝族自治州冕宁县"),

    SICHUANSHENGLIANGSHANYIZUZIZHIZHOUYUEXIXIAN(513434, "四川省凉山彝族自治州越西县"), SICHUANSHENGLIANGSHANYIZUZIZHIZHOUGANLUOXIAN(513435, "四川省凉山彝族自治州甘洛县"),

    SICHUANSHENGLIANGSHANYIZUZIZHIZHOUMEIGUXIAN(513436, "四川省凉山彝族自治州美姑县"), SICHUANSHENGLIANGSHANYIZUZIZHIZHOULEIBOXIAN(513437, "四川省凉山彝族自治州雷波县"),

    SICHUANSHENGBAZHONGDIQU(513700, "四川省巴中地区"), SICHUANSHENGBAZHONGDIQUBAZHONGSHI(513701, "四川省巴中地区巴中市"),

    SICHUANSHENGBAZHONGDIQUTONGJIANGXIAN(513721, "四川省巴中地区通江县"), SICHUANSHENGBAZHONGDIQUNANJIANGXIAN(513722, "四川省巴中地区南江县"),

    SICHUANSHENGBAZHONGDIQUPINGCHANGXIAN(513723, "四川省巴中地区平昌县"), SICHUANSHENGMEISHANDIQU(513800, "四川省眉山地区"),

    SICHUANSHENGMEISHANDIQUMEISHANXIAN(513821, "四川省眉山地区眉山县"), SICHUANSHENGMEISHANDIQURENSHOUXIAN(513822, "四川省眉山地区仁寿县"),

    SICHUANSHENGMEISHANDIQUPENGSHANXIAN(513823, "四川省眉山地区彭山县"), SICHUANSHENGMEISHANDIQUHONGYAXIAN(513824, "四川省眉山地区洪雅县"),

    SICHUANSHENGMEISHANDIQUDANLENGXIAN(513825, "四川省眉山地区丹棱县"), SICHUANSHENGMEISHANDIQUQINGSHENXIAN(513826, "四川省眉山地区青神县"),

    SICHUANSHENGMEISHANDIQUZIYANGDIQU(513900, "四川省眉山地区资阳地区"), SICHUANSHENGMEISHANDIQUZIYANGSHI(513901, "四川省眉山地区资阳市"),

    SICHUANSHENGMEISHANDIQUJIANYANGSHI(513902, "四川省眉山地区简阳市"), SICHUANSHENGMEISHANDIQUANYUEXIAN(513921, "四川省眉山地区安岳县"),

    SICHUANSHENGMEISHANDIQULEZHIXIAN(513922, "四川省眉山地区乐至县"), GUIZHOUSHENG(520000, "贵州省"),

    GUIZHOUSHENGGUIYANGSHI(520100, "贵州省贵阳市"), GUIZHOUSHENGGUIYANGSHISHIXIAQU(520101, "贵州省贵阳市市辖区"),

    GUIZHOUSHENGGUIYANGSHINANMINGQU(520102, "贵州省贵阳市南明区"), GUIZHOUSHENGGUIYANGSHIYUNYANQU(520103, "贵州省贵阳市云岩区"),

    GUIZHOUSHENGGUIYANGSHIHUAXIQU(520111, "贵州省贵阳市花溪区"), GUIZHOUSHENGGUIYANGSHIWUDANGQU(520112, "贵州省贵阳市乌当区"),

    GUIZHOUSHENGGUIYANGSHIBAIYUNQU(520113, "贵州省贵阳市白云区"), GUIZHOUSHENGGUIYANGSHIKAIYANGXIAN(520121, "贵州省贵阳市开阳县"),

    GUIZHOUSHENGGUIYANGSHIXIFENGXIAN(520122, "贵州省贵阳市息烽县"), GUIZHOUSHENGGUIYANGSHIXIUWENXIAN(520123, "贵州省贵阳市修文县"),

    GUIZHOUSHENGGUIYANGSHIQINGZHENSHI(520181, "贵州省贵阳市清镇市"), GUIZHOUSHENGLIUPANSHUISHI(520200, "贵州省六盘水市"),

    GUIZHOUSHENGLIUPANSHUISHIZHONGSHANQU(520201, "贵州省六盘水市钟山区"), GUIZHOUSHENGLIUPANSHUISHIPANXIANTEQU(520202, "贵州省六盘水市盘县特区"),

    GUIZHOUSHENGLIUPANSHUISHILIUZHITEQU(520203, "贵州省六盘水市六枝特区"), GUIZHOUSHENGLIUPANSHUISHISHUICHENGXIAN(520221, "贵州省六盘水市水城县"),

    GUIZHOUSHENGZUNYISHI(520300, "贵州省遵义市"), GUIZHOUSHENGZUNYISHISHIXIAQU(520301, "贵州省遵义市市辖区"),

    GUIZHOUSHENGZUNYISHIHONGHUAGANGQU(520302, "贵州省遵义市红花岗区"), GUIZHOUSHENGZUNYISHIZUNYIXIAN(520321, "贵州省遵义市遵义县"),

    GUIZHOUSHENGZUNYISHITONGZIXIAN(520322, "贵州省遵义市桐梓县"), GUIZHOUSHENGZUNYISHISUIYANGXIAN(520323, "贵州省遵义市绥阳县"),

    GUIZHOUSHENGZUNYISHIZHENGANXIAN(520324, "贵州省遵义市正安县"), GUIZHOUSHENGZUNYISHIDAOZHENGELAOZUMIAOZUZIZHIXIAN(520325, "贵州省遵义市道真仡佬族苗族自治县"),

    GUIZHOUSHENGZUNYISHIWUCHUANGELAOZUMIAOZUZIZHIXIAN(520326, "贵州省遵义市务川仡佬族苗族自治县"), GUIZHOUSHENGZUNYISHIFENGGANGXIAN(520327, "贵州省遵义市凤冈县"),

    GUIZHOUSHENGZUNYISHIMEITANXIAN(520328, "贵州省遵义市湄潭县"), GUIZHOUSHENGZUNYISHIYUQINGXIAN(520329, "贵州省遵义市余庆县"),

    GUIZHOUSHENGZUNYISHIXISHUIXIAN(520330, "贵州省遵义市习水县"), GUIZHOUSHENGZUNYISHICHISHUISHI(520381, "贵州省遵义市赤水市"),

    GUIZHOUSHENGZUNYISHIRENHUAISHI(520382, "贵州省遵义市仁怀市"), GUIZHOUSHENGTONGRENDIQU(522200, "贵州省铜仁地区"),

    GUIZHOUSHENGTONGRENDIQUTONGRENSHI(522201, "贵州省铜仁地区铜仁市"), GUIZHOUSHENGTONGRENDIQUJIANGKOUXIAN(522222, "贵州省铜仁地区江口县"),

    GUIZHOUSHENGTONGRENDIQUYUPINGDONGZUZIZHIXIAN(522223, "贵州省铜仁地区玉屏侗族自治县"), GUIZHOUSHENGTONGRENDIQUSHIQIANXIAN(522224, "贵州省铜仁地区石阡县"),

    GUIZHOUSHENGTONGRENDIQUSINANXIAN(522225, "贵州省铜仁地区思南县"), GUIZHOUSHENGTONGRENDIQUYINJIANGTUJIAZUMIAOZUZIZHIXIAN(522226, "贵州省铜仁地区印江土家族苗族自治县"),

    GUIZHOUSHENGTONGRENDIQUDEJIANGXIAN(522227, "贵州省铜仁地区德江县"), GUIZHOUSHENGTONGRENDIQUYANHETUJIAZUZIZHIXIAN(522228, "贵州省铜仁地区沿河土家族自治县"),

    GUIZHOUSHENGTONGRENDIQUSONGTAOMIAOZUZIZHIXIAN(522229, "贵州省铜仁地区松桃苗族自治县"), GUIZHOUSHENGTONGRENDIQUWANSHANTEQU(522230, "贵州省铜仁地区万山特区"),

    GUIZHOUSHENGQIANXINANBUYIZUMIAOZUZIZHIZHOU(522300, "贵州省黔西南布依族苗族自治州"), GUIZHOUSHENGQIANXINANBUYIZUMIAOZUZIZHIZHOUXINGYISHI(522301, "贵州省黔西南布依族苗族自治州兴义市"),

    GUIZHOUSHENGQIANXINANBUYIZUMIAOZUZIZHIZHOUXINGRENXIAN(522322, "贵州省黔西南布依族苗族自治州兴仁县"), GUIZHOUSHENGQIANXINANBUYIZUMIAOZUZIZHIZHOUPUANXIAN(522323, "贵州省黔西南布依族苗族自治州普安县"),

    GUIZHOUSHENGQIANXINANBUYIZUMIAOZUZIZHIZHOUQINGLONGXIAN(522324, "贵州省黔西南布依族苗族自治州晴隆县"), GUIZHOUSHENGQIANXINANBUYIZUMIAOZUZIZHIZHOUZHENFENGXIAN(522325, "贵州省黔西南布依族苗族自治州贞丰县"),

    GUIZHOUSHENGQIANXINANBUYIZUMIAOZUZIZHIZHOUWANGMOXIAN(522326, "贵州省黔西南布依族苗族自治州望谟县"), GUIZHOUSHENGQIANXINANBUYIZUMIAOZUZIZHIZHOUCEHENGXIAN(522327, "贵州省黔西南布依族苗族自治州册亨县"),

    GUIZHOUSHENGQIANXINANBUYIZUMIAOZUZIZHIZHOUANLONGXIAN(522328, "贵州省黔西南布依族苗族自治州安龙县"), GUIZHOUSHENGBIJIEDIQU(522400, "贵州省毕节地区"),

    GUIZHOUSHENGBIJIEDIQUBIJIESHI(522401, "贵州省毕节地区毕节市"), GUIZHOUSHENGBIJIEDIQUDAFANGXIAN(522422, "贵州省毕节地区大方县"),

    GUIZHOUSHENGBIJIEDIQUQIANXIXIAN(522423, "贵州省毕节地区黔西县"), GUIZHOUSHENGBIJIEDIQUJINSHAXIAN(522424, "贵州省毕节地区金沙县"),

    GUIZHOUSHENGBIJIEDIQUZHIJINXIAN(522425, "贵州省毕节地区织金县"), GUIZHOUSHENGBIJIEDIQUNAYONGXIAN(522426, "贵州省毕节地区纳雍县"),

    GUIZHOUSHENGBIJIEDIQUWEININGYIZUHUIZUMIAOZUZIZHIXIAN(522427, "贵州省毕节地区威宁彝族回族苗族自治县"), GUIZHOUSHENGBIJIEDIQUHEZHANGXIAN(522428, "贵州省毕节地区赫章县"),

    GUIZHOUSHENGANSHUNDIQU(522500, "贵州省安顺地区"), GUIZHOUSHENGANSHUNDIQUANSHUNSHI(522501, "贵州省安顺地区安顺市"),

    GUIZHOUSHENGANSHUNDIQUPINGBAXIAN(522526, "贵州省安顺地区平坝县"), GUIZHOUSHENGANSHUNDIQUPUDINGXIAN(522527, "贵州省安顺地区普定县"),

    GUIZHOUSHENGANSHUNDIQUGUANLINGBUYIZUMIAOZUZIZHIXIAN(522528, "贵州省安顺地区关岭布依族苗族自治县"), GUIZHOUSHENGANSHUNDIQUZHENNINGBUYIZUMIAOZUZIZHIXIAN(522529, "贵州省安顺地区镇宁布依族苗族自治县"),

    GUIZHOUSHENGANSHUNDIQUZIYUNMIAOZUBUYIZUZIZHIXIAN(522530, "贵州省安顺地区紫云苗族布依族自治县"), GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOU(522600, "贵州省黔东南苗族侗族自治州"),

    GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOUKAILISHI(522601, "贵州省黔东南苗族侗族自治州凯里市"), GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOUHUANGPINGXIAN(522622, "贵州省黔东南苗族侗族自治州黄平县"),

    GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOUSHIBINGXIAN(522623, "贵州省黔东南苗族侗族自治州施秉县"), GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOUSANSUIXIAN(522624, "贵州省黔东南苗族侗族自治州三穗县"),

    GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOUZHENYUANXIAN(522625, "贵州省黔东南苗族侗族自治州镇远县"), GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOUCENGONGXIAN(522626, "贵州省黔东南苗族侗族自治州岑巩县"),

    GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOUTIANZHUXIAN(522627, "贵州省黔东南苗族侗族自治州天柱县"), GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOUJINPINGXIAN(522628, "贵州省黔东南苗族侗族自治州锦屏县"),

    GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOUJIANHEXIAN(522629, "贵州省黔东南苗族侗族自治州剑河县"), GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOUTAIJIANGXIAN(522630, "贵州省黔东南苗族侗族自治州台江县"),

    GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOULIPINGXIAN(522631, "贵州省黔东南苗族侗族自治州黎平县"), GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOURONGJIANGXIAN(522632, "贵州省黔东南苗族侗族自治州榕江县"),

    GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOUCONGJIANGXIAN(522633, "贵州省黔东南苗族侗族自治州从江县"), GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOULEISHANXIAN(522634, "贵州省黔东南苗族侗族自治州雷山县"),

    GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOUMAJIANGXIAN(522635, "贵州省黔东南苗族侗族自治州麻江县"), GUIZHOUSHENGQIANDONGNANMIAOZUDONGZUZIZHIZHOUDANZHAIXIAN(522636, "贵州省黔东南苗族侗族自治州丹寨县"),

    GUIZHOUSHENGQIANNANBUYIZUMIAOZUZIZHIZHOU(522700, "贵州省黔南布依族苗族自治州"), GUIZHOUSHENGQIANNANBUYIZUMIAOZUZIZHIZHOUDOUYUNSHI(522701, "贵州省黔南布依族苗族自治州都匀市"),

    GUIZHOUSHENGQIANNANBUYIZUMIAOZUZIZHIZHOUFUQUANSHI(522702, "贵州省黔南布依族苗族自治州福泉市"), GUIZHOUSHENGQIANNANBUYIZUMIAOZUZIZHIZHOULIBOXIAN(522722, "贵州省黔南布依族苗族自治州荔波县"),

    GUIZHOUSHENGQIANNANBUYIZUMIAOZUZIZHIZHOUGUIDINGXIAN(522723, "贵州省黔南布依族苗族自治州贵定县"), GUIZHOUSHENGQIANNANBUYIZUMIAOZUZIZHIZHOUWENGANXIAN(522725, "贵州省黔南布依族苗族自治州瓮安县"),

    GUIZHOUSHENGQIANNANBUYIZUMIAOZUZIZHIZHOUDUSHANXIAN(522726, "贵州省黔南布依族苗族自治州独山县"), GUIZHOUSHENGQIANNANBUYIZUMIAOZUZIZHIZHOUPINGTANGXIAN(522727, "贵州省黔南布依族苗族自治州平塘县"),

    GUIZHOUSHENGQIANNANBUYIZUMIAOZUZIZHIZHOULUODIANXIAN(522728, "贵州省黔南布依族苗族自治州罗甸县"), GUIZHOUSHENGQIANNANBUYIZUMIAOZUZIZHIZHOUZHANGSHUNXIAN(522729, "贵州省黔南布依族苗族自治州长顺县"),

    GUIZHOUSHENGQIANNANBUYIZUMIAOZUZIZHIZHOULONGLIXIAN(522730, "贵州省黔南布依族苗族自治州龙里县"), GUIZHOUSHENGQIANNANBUYIZUMIAOZUZIZHIZHOUHUISHUIXIAN(522731, "贵州省黔南布依族苗族自治州惠水县"),

    GUIZHOUSHENGQIANNANBUYIZUMIAOZUZIZHIZHOUSANDOUSHUIZUZIZHIXIAN(522732, "贵州省黔南布依族苗族自治州三都水族自治县"), YUNNANSHENG(530000, "云南省"),

    YUNNANSHENGKUNMINGSHI(530100, "云南省昆明市"), YUNNANSHENGKUNMINGSHISHIXIAQU(530101, "云南省昆明市市辖区"),

    YUNNANSHENGKUNMINGSHIWUHUAQU(530102, "云南省昆明市五华区"), YUNNANSHENGKUNMINGSHIPANLONGQU(530103, "云南省昆明市盘龙区"),

    YUNNANSHENGKUNMINGSHIGUANDUQU(530111, "云南省昆明市官渡区"), YUNNANSHENGKUNMINGSHIXISHANQU(530112, "云南省昆明市西山区"),

    YUNNANSHENGKUNMINGSHIDONGCHUANQU(530113, "云南省昆明市东川区"), YUNNANSHENGKUNMINGSHICHENGGONGXIAN(530121, "云南省昆明市呈贡县"),

    YUNNANSHENGKUNMINGSHIJINNINGXIAN(530122, "云南省昆明市晋宁县"), YUNNANSHENGKUNMINGSHIFUMINXIAN(530124, "云南省昆明市富民县"),

    YUNNANSHENGKUNMINGSHIYILIANGXIAN(530125, "云南省昆明市宜良县"), YUNNANSHENGKUNMINGSHISHILINYIZUZIZHIXIAN(530126, "云南省昆明市石林彝族自治县"),

    YUNNANSHENGKUNMINGSHISONGMINGXIAN(530127, "云南省昆明市嵩明县"), YUNNANSHENGKUNMINGSHILUQUANYIZUMIAOZUZIZHIXIAN(530128, "云南省昆明市禄劝彝族苗族自治县"),

    YUNNANSHENGKUNMINGSHIXUNDIANHUIZUYIZUZIZHIXIAN(530129, "云南省昆明市寻甸回族彝族自治县"), YUNNANSHENGKUNMINGSHIANNINGSHI(530181, "云南省昆明市安宁市"),

    YUNNANSHENGQUJINGSHI(530300, "云南省曲靖市"), YUNNANSHENGQUJINGSHISHIXIAQU(530301, "云南省曲靖市市辖区"),

    YUNNANSHENGQUJINGSHIQILINQU(530302, "云南省曲靖市麒麟区"), YUNNANSHENGQUJINGSHIMALONGXIAN(530321, "云南省曲靖市马龙县"),

    YUNNANSHENGQUJINGSHILULIANGXIAN(530322, "云南省曲靖市陆良县"), YUNNANSHENGQUJINGSHISHIZONGXIAN(530323, "云南省曲靖市师宗县"),

    YUNNANSHENGQUJINGSHILUOPINGXIAN(530324, "云南省曲靖市罗平县"), YUNNANSHENGQUJINGSHIFUYUANXIAN(530325, "云南省曲靖市富源县"),

    YUNNANSHENGQUJINGSHIHUIZEXIAN(530326, "云南省曲靖市会泽县"), YUNNANSHENGQUJINGSHIZHANYIXIAN(530328, "云南省曲靖市沾益县"),

    YUNNANSHENGQUJINGSHIXUANWEISHI(530381, "云南省曲靖市宣威市"), YUNNANSHENGYUXISHI(530400, "云南省玉溪市"),

    YUNNANSHENGYUXISHISHIXIAQU(530401, "云南省玉溪市市辖区"), YUNNANSHENGYUXISHIHONGTAQU(530402, "云南省玉溪市红塔区"),

    YUNNANSHENGYUXISHIJIANGCHUANXIAN(530421, "云南省玉溪市江川县"), YUNNANSHENGYUXISHICHENGJIANGXIAN(530422, "云南省玉溪市澄江县"),

    YUNNANSHENGYUXISHITONGHAIXIAN(530423, "云南省玉溪市通海县"), YUNNANSHENGYUXISHIHUANINGXIAN(530424, "云南省玉溪市华宁县"),

    YUNNANSHENGYUXISHIYIMENXIAN(530425, "云南省玉溪市易门县"), YUNNANSHENGYUXISHIESHANYIZUZIZHIXIAN(530426, "云南省玉溪市峨山彝族自治县"),

    YUNNANSHENGYUXISHIXINPINGYIZUDAIZUZIZHIXIAN(530427, "云南省玉溪市新平彝族傣族自治县"), YUNNANSHENGYUXISHIYUANJIANGHANIZUYIZUDAIZUZIZHIXIAN(530428, "云南省玉溪市元江哈尼族彝族傣族自治县"),

    YUNNANSHENGZHAOTONGDIQU(532100, "云南省昭通地区"), YUNNANSHENGZHAOTONGDIQUZHAOTONGSHI(532101, "云南省昭通地区昭通市"),

    YUNNANSHENGZHAOTONGDIQULUDIANXIAN(532122, "云南省昭通地区鲁甸县"), YUNNANSHENGZHAOTONGDIQUQIAOJIAXIAN(532123, "云南省昭通地区巧家县"),

    YUNNANSHENGZHAOTONGDIQUYANJINXIAN(532124, "云南省昭通地区盐津县"), YUNNANSHENGZHAOTONGDIQUDAGUANXIAN(532125, "云南省昭通地区大关县"),

    YUNNANSHENGZHAOTONGDIQUYONGSHANXIAN(532126, "云南省昭通地区永善县"), YUNNANSHENGZHAOTONGDIQUSUIJIANGXIAN(532127, "云南省昭通地区绥江县"),

    YUNNANSHENGZHAOTONGDIQUZHENXIONGXIAN(532128, "云南省昭通地区镇雄县"), YUNNANSHENGZHAOTONGDIQUYILIANGXIAN(532129, "云南省昭通地区彝良县"),

    YUNNANSHENGZHAOTONGDIQUWEIXINXIAN(532130, "云南省昭通地区威信县"), YUNNANSHENGZHAOTONGDIQUSHUIFUXIAN(532131, "云南省昭通地区水富县"),

    YUNNANSHENGCHUXIONGYIZUZIZHIZHOU(532300, "云南省楚雄彝族自治州"), YUNNANSHENGCHUXIONGYIZUZIZHIZHOUCHUXIONGSHI(532301, "云南省楚雄彝族自治州楚雄市"),

    YUNNANSHENGCHUXIONGYIZUZIZHIZHOUSHUANGBOXIAN(532322, "云南省楚雄彝族自治州双柏县"), YUNNANSHENGCHUXIONGYIZUZIZHIZHOUMOUDINGXIAN(532323, "云南省楚雄彝族自治州牟定县"),

    YUNNANSHENGCHUXIONGYIZUZIZHIZHOUNANHUAXIAN(532324, "云南省楚雄彝族自治州南华县"), YUNNANSHENGCHUXIONGYIZUZIZHIZHOUYAOANXIAN(532325, "云南省楚雄彝族自治州姚安县"),

    YUNNANSHENGCHUXIONGYIZUZIZHIZHOUDAYAOXIAN(532326, "云南省楚雄彝族自治州大姚县"), YUNNANSHENGCHUXIONGYIZUZIZHIZHOUYONGRENXIAN(532327, "云南省楚雄彝族自治州永仁县"),

    YUNNANSHENGCHUXIONGYIZUZIZHIZHOUYUANMOUXIAN(532328, "云南省楚雄彝族自治州元谋县"), YUNNANSHENGCHUXIONGYIZUZIZHIZHOUWUDINGXIAN(532329, "云南省楚雄彝族自治州武定县"),

    YUNNANSHENGCHUXIONGYIZUZIZHIZHOULUFENGXIAN(532331, "云南省楚雄彝族自治州禄丰县"), YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOU(532500, "云南省红河哈尼族彝族自治州"),

    YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOUGEJIUSHI(532501, "云南省红河哈尼族彝族自治州个旧市"), YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOUKAIYUANSHI(532502, "云南省红河哈尼族彝族自治州开远市"),

    YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOUMENGZIXIAN(532522, "云南省红河哈尼族彝族自治州蒙自县"), YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOUPINGBIANMIAOZUZIZHIXIAN(532523, "云南省红河哈尼族彝族自治州屏边苗族自治县"),

    YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOUJIANSHUIXIAN(532524, "云南省红河哈尼族彝族自治州建水县"), YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOUSHIPINGXIAN(532525, "云南省红河哈尼族彝族自治州石屏县"),

    YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOUMILEXIAN(532526, "云南省红河哈尼族彝族自治州弥勒县"), YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOULUXIXIAN(532527, "云南省红河哈尼族彝族自治州泸西县"),

    YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOUYUANYANGXIAN(532528, "云南省红河哈尼族彝族自治州元阳县"), YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOUHONGHEXIAN(532529, "云南省红河哈尼族彝族自治州红河县"),

    YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOUJINPINGMIAOZUYAOZUDAIZUZIZHIXIAN(532530, "云南省红河哈尼族彝族自治州金平苗族瑶族傣族自治县"), YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOULUCHUNXIAN(532531, "云南省红河哈尼族彝族自治州绿春县"), YUNNANSHENGHONGHEHANIZUYIZUZIZHIZHOUHEKOUYAOZUZIZHIXIAN(532532, "云南省红河哈尼族彝族自治州河口瑶族自治县"),

    YUNNANSHENGWENSHANZHUANGZUMIAOZUZIZHIZHOU(532600, "云南省文山壮族苗族自治州"), YUNNANSHENGWENSHANZHUANGZUMIAOZUZIZHIZHOUWENSHANXIAN(532621, "云南省文山壮族苗族自治州文山县"),

    YUNNANSHENGWENSHANZHUANGZUMIAOZUZIZHIZHOUYANSHANXIAN(532622, "云南省文山壮族苗族自治州砚山县"), YUNNANSHENGWENSHANZHUANGZUMIAOZUZIZHIZHOUXICHOUXIAN(532623, "云南省文山壮族苗族自治州西畴县"),

    YUNNANSHENGWENSHANZHUANGZUMIAOZUZIZHIZHOUMALIPOXIAN(532624, "云南省文山壮族苗族自治州麻栗坡县"), YUNNANSHENGWENSHANZHUANGZUMIAOZUZIZHIZHOUMAGUANXIAN(532625, "云南省文山壮族苗族自治州马关县"),

    YUNNANSHENGWENSHANZHUANGZUMIAOZUZIZHIZHOUQIUBEIXIAN(532626, "云南省文山壮族苗族自治州丘北县"), YUNNANSHENGWENSHANZHUANGZUMIAOZUZIZHIZHOUGUANGNANXIAN(532627, "云南省文山壮族苗族自治州广南县"),

    YUNNANSHENGWENSHANZHUANGZUMIAOZUZIZHIZHOUFUNINGXIAN(532628, "云南省文山壮族苗族自治州富宁县"), YUNNANSHENGSIMAODIQU(532700, "云南省思茅地区"),

    YUNNANSHENGSIMAODIQUSIMAOSHI(532701, "云南省思茅地区思茅市"), YUNNANSHENGSIMAODIQUPUERHANIZUYIZUZIZHIXIAN(532722, "云南省思茅地区普洱哈尼族彝族自治县"),

    YUNNANSHENGSIMAODIQUMOJIANGHANIZUZIZHIXIAN(532723, "云南省思茅地区墨江哈尼族自治县"), YUNNANSHENGSIMAODIQUJINGDONGYIZUZIZHIXIAN(532724, "云南省思茅地区景东彝族自治县"),

    YUNNANSHENGSIMAODIQUJINGGUDAIZUYIZUZIZHIXIAN(532725, "云南省思茅地区景谷傣族彝族自治县"), YUNNANSHENGSIMAODIQUZHENYUANYIZUHANIZULAHUZUZIZHIXIAN(532726, "云南省思茅地区镇沅彝族哈尼族拉祜族自治县"),

    YUNNANSHENGSIMAODIQUJIANGCHENGHANIZUYIZUZIZHIXIAN(532727, "云南省思茅地区江城哈尼族彝族自治县"), YUNNANSHENGSIMAODIQUMENGLIANDAIZULAHUZUWAZUZIZHIXIAN(532728, "云南省思茅地区孟连傣族拉祜族佤族自治县"),

    YUNNANSHENGSIMAODIQULANCANGLAHUZUZIZHIXIAN(532729, "云南省思茅地区澜沧拉祜族自治县"), YUNNANSHENGSIMAODIQUXIMENGWAZUZIZHIXIAN(532730, "云南省思茅地区西盟佤族自治县"),

    YUNNANSHENGXISHUANGBANNADAIZUZIZHIZHOU(532800, "云南省西双版纳傣族自治州"), YUNNANSHENGXISHUANGBANNADAIZUZIZHIZHOUJINGHONGSHI(532801, "云南省西双版纳傣族自治州景洪市"),

    YUNNANSHENGXISHUANGBANNADAIZUZIZHIZHOUMENGHAIXIAN(532822, "云南省西双版纳傣族自治州勐海县"), YUNNANSHENGXISHUANGBANNADAIZUZIZHIZHOUMENGLAXIAN(532823, "云南省西双版纳傣族自治州勐腊县"),

    YUNNANSHENGDALIBAIZUZIZHIZHOU(532900, "云南省大理白族自治州"), YUNNANSHENGDALIBAIZUZIZHIZHOUDALISHI(532901, "云南省大理白族自治州大理市"),

    YUNNANSHENGDALIBAIZUZIZHIZHOUYANGBIYIZUZIZHIXIAN(532922, "云南省大理白族自治州漾濞彝族自治县"), YUNNANSHENGDALIBAIZUZIZHIZHOUXIANGYUNXIAN(532923, "云南省大理白族自治州祥云县"),

    YUNNANSHENGDALIBAIZUZIZHIZHOUBINCHUANXIAN(532924, "云南省大理白族自治州宾川县"), YUNNANSHENGDALIBAIZUZIZHIZHOUMIDUXIAN(532925, "云南省大理白族自治州弥渡县"),

    YUNNANSHENGDALIBAIZUZIZHIZHOUNANJIANYIZUZIZHIXIAN(532926, "云南省大理白族自治州南涧彝族自治县"), YUNNANSHENGDALIBAIZUZIZHIZHOUWEISHANYIZUHUIZUZIZHIXIAN(532927, "云南省大理白族自治州巍山彝族回族自治县"),

    YUNNANSHENGDALIBAIZUZIZHIZHOUYONGPINGXIAN(532928, "云南省大理白族自治州永平县"), YUNNANSHENGDALIBAIZUZIZHIZHOUYUNLONGXIAN(532929, "云南省大理白族自治州云龙县"),

    YUNNANSHENGDALIBAIZUZIZHIZHOUERYUANXIAN(532930, "云南省大理白族自治州洱源县"), YUNNANSHENGDALIBAIZUZIZHIZHOUJIANCHUANXIAN(532931, "云南省大理白族自治州剑川县"),

    YUNNANSHENGDALIBAIZUZIZHIZHOUHEQINGXIAN(532932, "云南省大理白族自治州鹤庆县"), YUNNANSHENGBAOSHANDIQU(533000, "云南省保山地区"),

    YUNNANSHENGBAOSHANDIQUBAOSHANSHI(533001, "云南省保山地区保山市"), YUNNANSHENGBAOSHANDIQUSHIDIANXIAN(533022, "云南省保山地区施甸县"),

    YUNNANSHENGBAOSHANDIQUTENGCHONGXIAN(533023, "云南省保山地区腾冲县"), YUNNANSHENGBAOSHANDIQULONGLINGXIAN(533024, "云南省保山地区龙陵县"),

    YUNNANSHENGBAOSHANDIQUCHANGNINGXIAN(533025, "云南省保山地区昌宁县"), YUNNANSHENGDEHONGDAIZUJINGPOZUZIZHIZHOU(533100, "云南省德宏傣族景颇族自治州"),

    YUNNANSHENGDEHONGDAIZUJINGPOZUZIZHIZHOUWANDINGSHI(533101, "云南省德宏傣族景颇族自治州畹町市"), YUNNANSHENGDEHONGDAIZUJINGPOZUZIZHIZHOURUILISHI(533102, "云南省德宏傣族景颇族自治州瑞丽市"),

    YUNNANSHENGDEHONGDAIZUJINGPOZUZIZHIZHOULUXISHI(533103, "云南省德宏傣族景颇族自治州潞西市"), YUNNANSHENGDEHONGDAIZUJINGPOZUZIZHIZHOULIANGHEXIAN(533122, "云南省德宏傣族景颇族自治州梁河县"),

    YUNNANSHENGDEHONGDAIZUJINGPOZUZIZHIZHOUYINGJIANGXIAN(533123, "云南省德宏傣族景颇族自治州盈江县"), YUNNANSHENGDEHONGDAIZUJINGPOZUZIZHIZHOULONGCHUANXIAN(533124, "云南省德宏傣族景颇族自治州陇川县"),

    YUNNANSHENGLIJIANGDIQU(533200, "云南省丽江地区"), YUNNANSHENGLIJIANGDIQULIJIANGNAXIZUZIZHIXIAN(533221, "云南省丽江地区丽江纳西族自治县"),

    YUNNANSHENGLIJIANGDIQUYONGSHENGXIAN(533222, "云南省丽江地区永胜县"), YUNNANSHENGLIJIANGDIQUHUAPINGXIAN(533223, "云南省丽江地区华坪县"),

    YUNNANSHENGLIJIANGDIQUNINGLANGYIZUZIZHIXIAN(533224, "云南省丽江地区宁蒗彝族自治县"), YUNNANSHENGNUJIANGLISUZUZIZHIZHOU(533300, "云南省怒江傈僳族自治州"),

    YUNNANSHENGNUJIANGLISUZUZIZHIZHOULUSHUIXIAN(533321, "云南省怒江傈僳族自治州泸水县"), YUNNANSHENGNUJIANGLISUZUZIZHIZHOUFUGONGXIAN(533323, "云南省怒江傈僳族自治州福贡县"),

    YUNNANSHENGNUJIANGLISUZUZIZHIZHOUGONGSHANDULONGZUNUZUZIZHIXIAN(533324, "云南省怒江傈僳族自治州贡山独龙族怒族自治县"), YUNNANSHENGNUJIANGLISUZUZIZHIZHOULANPINGBAIZUPUMIZUZIZHIXIAN(533325, "云南省怒江傈僳族自治州兰坪白族普米族自治县"),

    YUNNANSHENGDIQINGZANGZUZIZHIZHOU(533400, "云南省迪庆藏族自治州"), YUNNANSHENGDIQINGZANGZUZIZHIZHOUZHONGDIANXIAN(533421, "云南省迪庆藏族自治州中甸县"),

    YUNNANSHENGDIQINGZANGZUZIZHIZHOUDEQINXIAN(533422, "云南省迪庆藏族自治州德钦县"), YUNNANSHENGDIQINGZANGZUZIZHIZHOUWEIXILISUZUZIZHIXIAN(533423, "云南省迪庆藏族自治州维西傈僳族自治县"),

    YUNNANSHENGLINCANGDIQU(533500, "云南省临沧地区"), YUNNANSHENGLINCANGDIQULINCANGXIAN(533521, "云南省临沧地区临沧县"),

    YUNNANSHENGLINCANGDIQUFENGQINGXIAN(533522, "云南省临沧地区凤庆县"), YUNNANSHENGLINCANGDIQUYUNXIAN(533523, "云南省临沧地区云县"),

    YUNNANSHENGLINCANGDIQUYONGDEXIAN(533524, "云南省临沧地区永德县"), YUNNANSHENGLINCANGDIQUZHENKANGXIAN(533525, "云南省临沧地区镇康县"),

    YUNNANSHENGLINCANGDIQUSHUANGJIANGLAHUZUWAZUBULANGZUDAIZUZIZHIXIAN(533526, "云南省临沧地区双江拉祜族佤族布朗族傣族自治县"), YUNNANSHENGLINCANGDIQUGENGMADAIZUWAZUZIZHIXIAN(533527, "云南省临沧地区耿马傣族佤族自治县"),

    YUNNANSHENGLINCANGDIQUCANGYUANWAZUZIZHIXIAN(533528, "云南省临沧地区沧源佤族自治县"), XIZANGZIZHIQU(540000, "西藏自治区"),

    XIZANGZIZHIQULASASHI(540100, "西藏自治区拉萨市"), XIZANGZIZHIQULASASHISHIXIAQU(540101, "西藏自治区拉萨市市辖区"),

    XIZANGZIZHIQULASASHICHENGGUANQU(540102, "西藏自治区拉萨市城关区"), XIZANGZIZHIQULASASHILINZHOUXIAN(540121, "西藏自治区拉萨市林周县"),

    XIZANGZIZHIQULASASHIDANGXIONGXIAN(540122, "西藏自治区拉萨市当雄县"), XIZANGZIZHIQULASASHINIMUXIAN(540123, "西藏自治区拉萨市尼木县"),

    XIZANGZIZHIQULASASHIQUSHUIXIAN(540124, "西藏自治区拉萨市曲水县"), XIZANGZIZHIQULASASHIDUILONGDEQINGXIAN(540125, "西藏自治区拉萨市堆龙德庆县"),

    XIZANGZIZHIQULASASHIDAZIXIAN(540126, "西藏自治区拉萨市达孜县"), XIZANGZIZHIQULASASHIMOZHUGONGKAXIAN(540127, "西藏自治区拉萨市墨竹工卡县"),

    XIZANGZIZHIQUCHANGDOUDIQU(542100, "西藏自治区昌都地区"), XIZANGZIZHIQUCHANGDOUDIQUCHANGDOUXIAN(542121, "西藏自治区昌都地区昌都县"),

    XIZANGZIZHIQUCHANGDOUDIQUJIANGDAXIAN(542122, "西藏自治区昌都地区江达县"), XIZANGZIZHIQUCHANGDOUDIQUGONGJUEXIAN(542123, "西藏自治区昌都地区贡觉县"),

    XIZANGZIZHIQUCHANGDOUDIQULEIWUQIXIAN(542124, "西藏自治区昌都地区类乌齐县"), XIZANGZIZHIQUCHANGDOUDIQUDINGQINGXIAN(542125, "西藏自治区昌都地区丁青县"),

    XIZANGZIZHIQUCHANGDOUDIQUCHAYAXIAN(542126, "西藏自治区昌都地区察雅县"), XIZANGZIZHIQUCHANGDOUDIQUBASUXIAN(542127, "西藏自治区昌都地区八宿县"),

    XIZANGZIZHIQUCHANGDOUDIQUZUOGONGXIAN(542128, "西藏自治区昌都地区左贡县"), XIZANGZIZHIQUCHANGDOUDIQUMANGKANGXIAN(542129, "西藏自治区昌都地区芒康县"),

    XIZANGZIZHIQUCHANGDOUDIQULUOLONGXIAN(542132, "西藏自治区昌都地区洛隆县"), XIZANGZIZHIQUCHANGDOUDIQUBIANBAXIAN(542133, "西藏自治区昌都地区边坝县"),

    XIZANGZIZHIQUCHANGDOUDIQUYANJINGXIAN(542134, "西藏自治区昌都地区盐井县"), XIZANGZIZHIQUCHANGDOUDIQUBITUXIAN(542135, "西藏自治区昌都地区碧土县"),

    XIZANGZIZHIQUCHANGDOUDIQUTUOBAXIAN(542136, "西藏自治区昌都地区妥坝县"), XIZANGZIZHIQUCHANGDOUDIQUSHENGDAXIAN(542137, "西藏自治区昌都地区生达县"),

    XIZANGZIZHIQUSHANNANDIQU(542200, "西藏自治区山南地区"), XIZANGZIZHIQUSHANNANDIQUNAIDONGXIAN(542221, "西藏自治区山南地区乃东县"),

    XIZANGZIZHIQUSHANNANDIQUZHANANGXIAN(542222, "西藏自治区山南地区扎囊县"), XIZANGZIZHIQUSHANNANDIQUGONGGAXIAN(542223, "西藏自治区山南地区贡嘎县"),

    XIZANGZIZHIQUSHANNANDIQUSANGRIXIAN(542224, "西藏自治区山南地区桑日县"), XIZANGZIZHIQUSHANNANDIQUQIONGJIEXIAN(542225, "西藏自治区山南地区琼结县"),

    XIZANGZIZHIQUSHANNANDIQUQUSONGXIAN(542226, "西藏自治区山南地区曲松县"), XIZANGZIZHIQUSHANNANDIQUCUOMEIXIAN(542227, "西藏自治区山南地区措美县"),

    XIZANGZIZHIQUSHANNANDIQULUOZHAXIAN(542228, "西藏自治区山南地区洛扎县"), XIZANGZIZHIQUSHANNANDIQUJIACHAXIAN(542229, "西藏自治区山南地区加查县"),

    XIZANGZIZHIQUSHANNANDIQULONGZIXIAN(542231, "西藏自治区山南地区隆子县"), XIZANGZIZHIQUSHANNANDIQUCUONEIXIAN(542232, "西藏自治区山南地区错那县");

    private int code;
    private String area;

    Area2(int code, String area) {
        this.code = code;
        this.area = area;
    }

    public int getCode() {
        return code;
    }

    public String getArea() {
        return area;
    }

    public static void main(String[] args) {
        System.out.println("1");
    }
    public static String getAreaByCode(Integer code) {


        if (code == null) {
            return null;
        }
        int valueKey = code;

        for (Area2 enums : Area2.values()) {
            if (enums.getCode() == valueKey) {
                return enums.getArea();
            }
        }
        return null;
    }
}
